### ISSUE TITLE
Timezone from TZ Aware datetime string

### ISSUE THREAD

**Issue by neotheicebird** [kennethreitz/maya#148]
When I tried to parse this string looking for the timezone:

`maya.parse('2018-04-23T12:00:00+05:30').timezone` which is `Asia/Kolkata` the response is `UTC`. Is this by design?

I understand the `.local_timezone` gives the timezone of the machine, which is also not what I am looking for.

If a human being reads `2018-04-23T12:00:00+05:30` I think they will assume, 12oclock in Kolkata or somewhere in india.

**Comment by timofurrer** [comment]
> Is this by design?

Yes, this is by design. Maya always converts the parsed datetimes to UTC.
That's what allows what's listed here: [Why is this useful](https://github.com/kennethreitz/maya#-why-is-this-useful)

If you want to convert it back from a `MayaDT` instance to a timezone aware `datetime` object you can do the following:

```pycon
>>> m = maya.parse('2018-04-23T12:00:00+05:30')
>>> m.datetime()
datetime.datetime(2018, 4, 23, 6, 30, tzinfo=<UTC>)
>>> m.datetime(to_timezone='Asia/Kolkata')
datetime.datetime(2018, 4, 23, 12, 0, tzinfo=<DstTzInfo 'Asia/Kolkata' IST+5:30:00 STD>)
```
