### ISSUE TITLE
transfer back to @kennethreitz

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/maya#203]
up for it? :)

**Comment by timofurrer** [comment]
@kennethreitz welcome back Kenneth! 🎉 

Perfectly for https://github.com/timofurrer/maya/issues/197.

***

However, I'm unable to transfer ownership, because you already have a fork at https://github.com/kennethreitz/maya. Please remove it first and let me know when you are ready for the transfer! Looking forward to it!

**Comment by kennethreitz** [comment]
Many thanks! Okay I deleted the fork.

**Comment by timofurrer** [comment]
@kennethreitz I've requested the transfer!

**Comment by kennethreitz** [comment]
@timofurrer thanks so much!

**Comment by timofurrer** [comment]
Great to see it survive, hopefully! 😎
