### ISSUE TITLE
Improve validate_type_mayadt decorator

### ISSUE THREAD

**Issue by timofurrer** [kennethreitz/maya#33]
In my opinion not only the Python object API has to be sane for humans but also (and maybe even more) the error messages.

There is this `validate_type_mayadt` decorator which throws a `ValueError` exception if the given arguments are not of type `MayaDT` with a somehow insufficient error message. It'd be great if it would actually tell us which operation failed because of the type mismatch. 

Which operation failed?
```python
assert (dt1 == dt2) >= 1
```

I see multiple solutions here:

1. pass a decorator argument describing the operation: `@validate('less than')`
2. get the function name from the `func` object within the decorator: `func.__name__`
3. ...

However, point 2 leads to an `unhumanized` error message because `__lt__` would be printed - yes we could argue this exception only occurs due to programming error - It'd favor the first one though.

What do you think?

And the resulting exception should be of type [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError)

**Comment by moin18** [comment]
A decorated function is slower than the undecorated version, not just because of the extra work it performs, but also because you get an extra level of function call every time you call the decorated function. And that's going to be be really noticeable with comparison functions when you try to perform a sort. 

IMHO,  we should remove this decorator and make explicit check within the each comparison.

> Explicit checks? Won't we be writing same logic in each function call?

For this case, Performance takes precedence, since we often need to call comparison methods in loops, so they should be as optimized as we can make them.

**Comment by moin18** [comment]
It'd probably be more efficient to assume the objects being compared are of compatible types, and use `try: ... except` to deal with incompatible objects.
Python's `try: ... except` is very fast when the exception isn't actually raised, much faster than the equivalent if-based code. It is even better to use `try:...except` here.

Will be raising a PR in a while.

**Comment by kennethreitz** [comment]
Thanks!
