### ISSUE TITLE
Support the "Anywhere on Earth" designation

### ISSUE THREAD

**Issue by davidism** [kennethreitz/maya#80]
https://en.wikipedia.org/wiki/Anywhere_on_Earth

> Anywhere on Earth (AoE) is a calendar designation which indicates that a period expires when the date passes everywhere on Earth.

I learned about this from the [PSF election](https://wiki.python.org/moin/PythonSoftwareFoundation/BoardCandidates2017), which specifies its start and end dates using this. Stack Overflow uses it for many of its events (I think, they don't use the term directly).

* `MayaDT.aoe()` would be true if it is that date anywhere on Earth
* `MayaInterval.aoe()` would be true if the interval was current anywhere on Earth

<sub>`aoe` name subject to change</sub>

**Comment by moin18** [comment]
I think we should do this. It's a nice suggestion.

@kennethreitz What are your thoughts over this?

**Comment by timofurrer** [comment]
I'd like to see that feature too!

**Comment by kennethreitz** [comment]
I also discovered this from the PSF recently, and was doing some research to see if we could add it to this library!

**Comment by moin18** [comment]
On a second thought, I feel this isn't a good fit for Maya because the core of Maya is based on the fact it uses UTC for the all the operations and doesn't care about different timezones. As per me , adding a operation that takes into account the timezones across the globe is not something for which Maya was initially constructed.

I have a mixed/confused opinion regarding this feature request.

**Comment by kennethreitz** [comment]
I don't disagree.
