### ISSUE TITLE
Should Return 'UTC' if get_localzone returns an invalid pytz zone name.

### ISSUE THREAD

**Issue by ibigpapa** [kennethreitz/maya#89]
When I get an error when using slang_time due to `tzlocal` returning `local` as the timezone when using the `python:alpine` docker container.

I've also submitted an issue to the tzlocal maintainer https://github.com/regebro/tzlocal/issues/44

Steps to recreate
1.  Get into shell of container: `docker run --rm -it python:alpine /bin/sh`
2.  Install dependencies: `apk --no-cache add g++ musl-dev linux-headers`
3.  Install `maya`: `pip install maya`
4.  Launch python: `python`
5.  Import and test:
```python
>>> import maya
>>> maya.when('2hr from now')
<MayaDT epoch=1498681971.941609>

>>> maya.when('7200 seconds from now')
<MayaDT epoch=1498682137.486269>

>>> maya.when(f'{7200} seconds from now').slang_time()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/maya/core.py", line 259, in slang_time
    dt = self.datetime(naive=True, to_timezone=self.local_timezone)
  File "/usr/local/lib/python3.6/site-packages/maya/core.py", line 177, in datetime
    dt = self.datetime().astimezone(pytz.timezone(to_timezone))
  File "/usr/local/lib/python3.6/site-packages/pytz/__init__.py", line 181, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'local'
```

**Comment by regebro** [comment]
The problem here IMO is that Maya, everytime it makes a conversion of a datetime to a timezone, takes the name in the tzinfo object and passes it to pytz to look up a new tzinfo object. That's unecessary, you'll just get the same object back, so it's a roundtrip with little point, and it also means it will only work with timezones in the Olsen database included in the pytz version you are running.

I don't know if there is a reason for that design, but that's what causing this problem.

**Comment by benjaoming** [comment]
This is reported to be a problem too in Windows' Ubuntu Bash thing: learningequality/kolibri#2484

**Comment by timofurrer** [comment]
It seems like @kennethreitz merged a PR for this issue some months ago. 

Can this issue be closed?
